### ISSUE TITLE
Where is code for the mentioned "Long Text Generation: EMNLP2017 WMT News" experiment?

### ISSUE THREAD

**Issue by akanimax** [CR-Gjx/LeakGAN#13]
Hello @CR-Gjx @wnzhang. Firstly, Really great work with the LeakGAN framework. The paper is very aptly organised and is indeed very insightful. I have been reading the paper in order to understand the concepts of the framework. I am interested in the Long Text Generation experiment among all the others. In this repository, unfortunately, I couldn't find the code for this experiment (for the other two experiments, it's there). Could you point me to where it is? Thank you!

**Comment by CR-Gjx** [comment]
Hi, thanks for your attention. We have public the code for Synthetic Data experiment and Real Data experiment (Image Coco) if you want to try other real data experiments, you can replace the dataset which is in ImageCoco folder.
EMNLP WMT 2017: http://statmt.org/wmt17/translation-task.html
Poem: http://homepages.inf.ed.ac.uk/mlap/Data/EMNLP14/

**Comment by akanimax** [comment]
@CR-Gjx Thank you for the explanation!
