### ISSUE TITLE
An issue about your code 

### ISSUE THREAD

**Issue by Syrup274** [CR-Gjx/LeakGAN#3]
I am a little confused by your code _synthetic  data_ with sequence length 40.
The following code may replace the positive samples(real data) with LSTM generated ones. 
` generate_samples(sess, target_lstm, BATCH_SIZE, generated_num, positive_file, 0)`
Since the oracle LSTM does not reload parameters for pkl file, how could you treat the random initialized LSTM generated samples as  positive samples? 
Many thanks!

**Comment by CR-Gjx** [comment]
At the beginning of the `Main.py`, I import 2 different oracle. You can see that length-20 oracle initialize by reloading pkl file and length-40 oracle will initialize variable from random number.
