### ISSUE TITLE
Why CNN instead of LSTM?

### ISSUE THREAD

**Issue by AranKomat** [CR-Gjx/LeakGAN#7]
There are some recent text generation GAN papers in which the discriminator is a LSTM rather than a CNN. Why was CNN used in this paper?

**Comment by CR-Gjx** [comment]
1. This work is inherited from the SeqGAN (http://www.aaai.org/Conferences/AAAI/2017/PreliminaryPapers/12-Yu-L-14344.pdf), this work use CNN as a discriminator. Other good works like [RankGAN](https://arxiv.org/abs/1705.11001)
, [(Adversarial Feature Matching for Text Generation )](https://arxiv.org/pdf/1706.03850.pdf) are also use a CNN as a discriminator. 
2. CNN is a choice for a discriminator. In fact, we also try using LSTM as a discriminator, it also has a good performance, but limited by speed.

**Comment by AranKomat** [comment]
Thanks for your clarification and in particular telling my that LSTM worked not significantly better than CNN.

**Comment by CR-Gjx** [comment]
Sorry, I mean that LSTM limited by the speed because of its bad parallelization. While the performance of LSTM depends on the specific task.

**Comment by AranKomat** [comment]
I see. It'd be interesting to try with Transformer. Sorry but I have three questions remaining. 

1. In SeqGAN issue page, LantaoYu theoretically justified training G once for each 15 steps of D updates. But did you guys empirically verify that the 1:15 ratio was good? 

2. In the adversarial training, it was trained for 800 batches only. Is this small number due to fast convergence or considerable amount of training time? 

3. Does the discriminator of LeakGAN receive unfinished real sentences as well, to discriminate them from unfinished fake sentences? If all the discriminator receives are real finished sentences and fake finished and unfinished sentences, then it's trivial to discriminate them by judging the one with comma at the end to be real one. But in this way, the discriminator cannot learn much. How is this avoided in your algorithm?
